In [2]:
#Decision Tree Classifier and Hyperparameter tuning

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv('https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv',sep = ';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [8]:
#Basic Analysis

In [10]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [12]:
len(df['quality'].unique())

6

In [14]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [16]:
df.describe().T

count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   5.636023   0.807569  3.00000   5.0000   

                           50%        75%        max  
fixed acidity          7.90000   9.200000   15.90000  
volatile acidity       0.52000   0.640000    1.58000  
citric acid            0.26000   0.420000    1.00000  
residual sugar         2.20000   2.600000   15.50000  
chlorides              0.07900   0.090000    0.61100  
free sulfur dioxide   14.00000  21.000000   72.00000  
total sulfur dioxide  38.00000  62.000000  289.00000  
density                0.99675   0.997835    1.00369  
pH                     3.31000   3.400000    4.01000  
sulphates              0.62000   0.730000    2.00000  
alcohol               10.20000  11.100000   14.90000  
quality                6.00000   6.000000    8.00000

In [18]:
df.duplicated().sum()

240

In [20]:
df=df.drop_duplicates()

In [22]:
df.duplicated().sum()

0

In [24]:
X=df.drop('quality',axis=1)
y=df['quality']

In [26]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
5               7.4             0.660         0.00             1.8      0.075   
...             ...               ...          ...             ...        ...   
1593            6.8             0.620         0.08             1.9      0.068   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
5                    13.0                  40.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1593                 28.0                  38.0  0.99651  3.42       0.82   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
5         9.4  
...       ...  
1593      9.5  
1594     10.5  
1595     11.2  
1597     10.2  
1598     11.0  

[1359 rows x 11 columns]

In [28]:
y

0       5
1       5
2       5
3       6
5       5
       ..
1593    6
1594    5
1595    6
1597    5
1598    6
Name: quality, Length: 1359, dtype: int64

In [30]:
#Model building

In [32]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [34]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [36]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [38]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [40]:
from sklearn import tree
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(25,15))
tree.plot_tree(model, max_depth=4,filled=True)

[Text(0.49278846153846156, 0.9166666666666666, 'x[10] <= 10.15\ngini = 0.652\nsamples = 910\nvalue = [5, 38, 385, 354, 115, 13]'),
 Text(0.27884615384615385, 0.75, 'x[6] <= 91.5\ngini = 0.53\nsamples = 462\nvalue = [4.0, 24.0, 288.0, 129.0, 15.0, 2.0]'),
 Text(0.15384615384615385, 0.5833333333333334, 'x[1] <= 0.417\ngini = 0.575\nsamples = 377\nvalue = [4.0, 23.0, 212.0, 121.0, 15.0, 2.0]'),
 Text(0.07692307692307693, 0.4166666666666667, 'x[9] <= 0.655\ngini = 0.622\nsamples = 84\nvalue = [0, 2, 30, 41, 9, 2]'),
 Text(0.038461538461538464, 0.25, 'x[4] <= 0.079\ngini = 0.52\nsamples = 47\nvalue = [0.0, 1.0, 24.0, 22.0, 0.0, 0.0]'),
 Text(0.019230769230769232, 0.08333333333333333, '\n  (...)  \n'),
 Text(0.057692307692307696, 0.08333333333333333, '\n  (...)  \n'),
 Text(0.11538461538461539, 0.25, 'x[6] <= 31.5\ngini = 0.647\nsamples = 37\nvalue = [0, 1, 6, 19, 9, 2]'),
 Text(0.09615384615384616, 0.08333333333333333, '\n  (...)  \n'),
 Text(0.1346153846153846, 0.08333333333333333, '\n  (.

In [42]:
y_pred=model.predict(X_test)
y_pred

array([4, 6, 7, 7, 4, 7, 6, 5, 7, 6, 6, 7, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6,
       5, 5, 6, 5, 6, 5, 5, 6, 6, 7, 6, 4, 5, 6, 5, 6, 5, 7, 4, 5, 6, 5,
       6, 5, 5, 5, 6, 6, 6, 7, 5, 5, 5, 5, 4, 5, 5, 5, 5, 7, 5, 7, 5, 6,
       5, 6, 5, 7, 5, 8, 5, 6, 7, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 7, 5, 5,
       6, 6, 6, 5, 5, 6, 6, 6, 4, 7, 6, 5, 5, 5, 6, 5, 5, 6, 7, 6, 6, 7,
       6, 5, 5, 5, 5, 6, 4, 5, 5, 6, 5, 5, 6, 6, 5, 5, 4, 6, 5, 5, 5, 5,
       6, 5, 5, 5, 7, 6, 6, 5, 4, 5, 7, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5,
       6, 7, 6, 5, 7, 7, 8, 5, 5, 6, 5, 7, 6, 5, 7, 7, 6, 6, 8, 6, 7, 7,
       5, 6, 5, 7, 5, 5, 4, 5, 5, 6, 5, 5, 4, 7, 5, 5, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 7, 5, 7, 5, 7, 5, 6, 6, 5, 7, 6, 5, 5, 7, 5, 6, 6, 5, 6,
       6, 7, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 5, 6, 5, 5, 5,
       6, 5, 7, 6, 5, 7, 5, 7, 6, 6, 7, 6, 6, 8, 5, 5, 6, 6, 7, 5, 5, 5,
       6, 6, 5, 5, 6, 6, 6, 5, 7, 6, 5, 5, 6, 7, 4, 4, 5, 4, 5, 7, 6, 6,
       5, 5, 7, 7, 5, 6, 4, 6, 6, 5, 5, 7, 4, 5, 6,

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.46325167037861914

In [48]:
#Hyperparameter tuning

In [50]:
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,10,1),
    'min_samples_leaf' : range(1,8,1),
    'min_samples_split': range(2,8,1),
    'splitter' : ['best', 'random']
    
}

In [52]:
grid_search=GridSearchCV(estimator=model, param_grid=grid_param,cv=3,verbose=1)

In [54]:
grid_search.fit(X_train,y_train)

Fitting 3 folds for each of 1344 candidates, totalling 4032 fits


GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 10),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 8),
                         'splitter': ['best', 'random']},
             verbose=1)

In [56]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'min_samples_leaf': 5,
 'min_samples_split': 7,
 'splitter': 'random'}

In [58]:
model_with_best_param=DecisionTreeClassifier(criterion='entropy',max_depth=6,min_samples_leaf=7,min_samples_split=4,splitter='random')

In [60]:
model_with_best_param.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_leaf=7,
                       min_samples_split=4, splitter='random')

In [62]:
from sklearn import tree
import matplotlib.pyplot as plt
fig=plt.figure(figsize=(25,15))
tree.plot_tree(model_with_best_param,filled=True,fontsize=10)

[Text(0.5357142857142857, 0.9285714285714286, 'x[10] <= 10.832\nentropy = 1.752\nsamples = 910\nvalue = [5, 38, 385, 354, 115, 13]'),
 Text(0.2910714285714286, 0.7857142857142857, 'x[10] <= 9.971\nentropy = 1.522\nsamples = 625\nvalue = [4.0, 26.0, 339.0, 215.0, 39.0, 2.0]'),
 Text(0.16785714285714284, 0.6428571428571429, 'x[6] <= 114.833\nentropy = 1.338\nsamples = 392\nvalue = [4.0, 20.0, 254.0, 105.0, 8.0, 1.0]'),
 Text(0.10714285714285714, 0.5, 'x[2] <= 0.083\nentropy = 1.397\nsamples = 354\nvalue = [4, 19, 218, 104, 8, 1]'),
 Text(0.05714285714285714, 0.35714285714285715, 'x[3] <= 1.883\nentropy = 1.473\nsamples = 90\nvalue = [2, 11, 56, 20, 1, 0]'),
 Text(0.02857142857142857, 0.21428571428571427, 'x[2] <= 0.05\nentropy = 1.711\nsamples = 25\nvalue = [2, 5, 13, 5, 0, 0]'),
 Text(0.014285714285714285, 0.07142857142857142, 'entropy = 1.757\nsamples = 17\nvalue = [2, 5, 8, 2, 0, 0]'),
 Text(0.04285714285714286, 0.07142857142857142, 'entropy = 0.954\nsamples = 8\nvalue = [0, 0, 5, 3, 

In [64]:
y_pred2=model_with_best_param.predict(X_test)
y_pred2

array([5, 6, 6, 5, 4, 7, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 6,
       5, 5, 6, 5, 6, 5, 5, 4, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 4, 5, 6, 5,
       5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6,
       5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5,
       5, 6, 6, 6, 4, 5, 6, 6, 4, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6,
       6, 6, 5, 5, 5, 5, 6, 5, 6, 7, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5,
       6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5, 6,
       5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 7, 5, 6, 6, 6, 6,
       5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 7, 5, 5, 6, 7, 5,
       6, 6, 5, 6, 5, 7, 5, 6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6,
       5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 7, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5,
       6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 7, 6, 5,
       6, 5, 6, 6, 5, 6, 5, 5, 4, 5, 5, 6, 6, 5, 6,

In [66]:
accuracy_score(y_test,y_pred2)

0.5723830734966593

In [68]:
#Accuracy score before hyperparameter tuning: 0.46329621380846327
#Accuracy score after hyperparameter tuning: 0.5778841870824054