### Need to create user and movie vector to find the content vector

In [76]:
# import lib
import numpy as np
import pandas as pd

In [77]:
# read the movie dataset which is in u.item
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

In [78]:
items.head(5) # to see first 5 

movie id        movie title release date  video release date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   
3         4  Get Shorty (1995)  01-Jan-1995                 NaN   
4         5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDb URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1           1  ...        0          0       0        0   
1          1          0           0  ...        0          0       0        0   
2          0          0           0  ...        0          0       0        0   
3          0          0           0  ...        0          0       0        0   
4          0          0           0  ...        0          0       0        0   

   Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0       0         0    0        0  
1        0        0       0         1    0        0  
2        0        0       0         1    0        0  
3        0        0       0         0    0        0  
4        0        0       0         1    0        0  

[5 rows x 24 columns]

In [79]:
# selecting only needed items
movie_content = items[['movie id', 'movie title', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_content

movie id                                movie title  Action  Adventure  \
0            1                           Toy Story (1995)       0          0   
1            2                           GoldenEye (1995)       1          1   
2            3                          Four Rooms (1995)       0          0   
3            4                          Get Shorty (1995)       1          0   
4            5                             Copycat (1995)       0          0   
...        ...                                        ...     ...        ...   
1677      1678                          Mat' i syn (1997)       0          0   
1678      1679                           B. Monkey (1998)       0          0   
1679      1680                       Sliding Doors (1998)       0          0   
1680      1681                        You So Crazy (1994)       0          0   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)       0          0   

      Animation  Children's  Comedy  Crime  Documentary  Drama  Fantasy  \
0             1           1       1      0            0      0        0   
1             0           0       0      0            0      0        0   
2             0           0       0      0            0      0        0   
3             0           0       1      0            0      1        0   
4             0           0       0      1            0      1        0   
...         ...         ...     ...    ...          ...    ...      ...   
1677          0           0       0      0            0      1        0   
1678          0           0       0      0            0      0        0   
1679          0           0       0      0            0      1        0   
1680          0           0       1      0            0      0        0   
1681          0           0       0      0            0      1        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 20 columns]

In [80]:
# read the rating dataset
r_cols = ['user_id','movie_id','rating','unix_timestamp']
ratings =pd.read_csv('ml-100k/u.data',sep='\t',names =r_cols,encoding='latin-1')
ratings

user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [93]:
# to find the unique user count
n_user = ratings['user_id'].unique().shape[0]
n_user

943

In [81]:
# checking
ratings[ratings['user_id']==200][['movie_id','rating']]

movie_id  rating
12          222       5
189         673       5
243         318       5
326         304       5
367          96       5
...         ...     ...
88774      1028       2
90895       465       4
93200       139       3
94869       447       4
96573       523       4

[216 rows x 2 columns]

In [82]:
# pivot table
datamat = ratings.pivot_table(index ='user_id',columns='movie_id',values=ratings)
# datamat

In [83]:
data_matrix = datamat.replace(np.nan,0) # replace nan to 0
# data_matrix

In [84]:
# user Vector

user_vector = data_matrix.T # taking transpose for user vector
user_vector

user_id                  1    2    3    4    5    6    7    8    9    10   \
               movie_id                                                     
rating         1         5.0  4.0  0.0  0.0  4.0  4.0  0.0  0.0  0.0  4.0   
               2         3.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0   
               3         4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
               4         3.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0   
               5         3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
unix_timestamp 1678      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
               1679      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
               1680      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
               1681      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
               1682      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

user_id                  ...  934  935  936  937  938  939  940  941  942  943  
               movie_id  ...                                                    
rating         1         ...  2.0  3.0  4.0  0.0  4.0  0.0  0.0  5.0  0.0  0.0  
               2         ...  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
               3         ...  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
               4         ...  5.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  
               5         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...                      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
unix_timestamp 1678      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
               1679      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
               1680      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
               1681      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
               1682      ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[3364 rows x 943 columns]

In [34]:
# movie vector
movie_vec = items[['Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_vec.index=range(1,1683)

In [37]:
movie_vector = movie_vec.T
movie_vector

1     2     3     4     5     6     7     8     9     10    ...  \
Action          0     1     0     1     0     0     0     0     0     0  ...   
Adventure       0     1     0     0     0     0     0     0     0     0  ...   
Animation       1     0     0     0     0     0     0     0     0     0  ...   
Children's      1     0     0     0     0     0     0     1     0     0  ...   
Comedy          1     0     0     1     0     0     0     1     0     0  ...   
Crime           0     0     0     0     1     0     0     0     0     0  ...   
Documentary     0     0     0     0     0     0     0     0     0     0  ...   
Drama           0     0     0     1     1     1     1     1     1     1  ...   
Fantasy         0     0     0     0     0     0     0     0     0     0  ...   
Film-Noir       0     0     0     0     0     0     0     0     0     0  ...   
Horror          0     0     0     0     0     0     0     0     0     0  ...   
Musical         0     0     0     0     0     0     0     0     0     0  ...   
Mystery         0     0     0     0     0     0     0     0     0     0  ...   
Romance         0     0     0     0     0     0     0     0     0     0  ...   
Sci-Fi          0     0     0     0     0     0     1     0     0     0  ...   
Thriller        0     1     1     0     1     0     0     0     0     0  ...   
War             0     0     0     0     0     0     0     0     0     1  ...   
Western         0     0     0     0     0     0     0     0     0     0  ...   

             1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
Action          1     0     0     0     0     0     0     0     0     0  
Adventure       0     0     0     0     0     0     0     0     0     0  
Animation       0     0     0     0     0     0     0     0     0     0  
Children's      0     0     0     0     0     0     0     0     0     0  
Comedy          0     0     0     0     0     0     0     0     1     0  
Crime           0     0     0     0     0     0     0     0     0     0  
Documentary     0     0     0     0     0     0     0     0     0     0  
Drama           0     1     1     1     1     1     0     1     0     1  
Fantasy         0     0     0     0     0     0     0     0     0     0  
Film-Noir       0     0     0     0     0     0     0     0     0     0  
Horror          0     0     0     0     0     0     0     0     0     0  
Musical         0     0     0     0     0     0     0     0     0     0  
Mystery         0     0     0     0     0     0     0     0     0     0  
Romance         0     0     0     0     0     0     1     1     0     0  
Sci-Fi          0     0     0     0     0     0     0     0     0     0  
Thriller        1     0     0     0     0     0     1     0     0     0  
War             0     0     0     0     0     0     0     0     0     0  
Western         0     0     0     0     0     0     0     0     0     0  

[18 rows x 1682 columns]

In [86]:
# checking for user == 1
u1 = ratings[ratings['user_id']==1][['movie_id','rating']]
u1

movie_id  rating
202          61       4
305         189       3
333          33       4
334         160       4
478          20       4
...         ...     ...
92049        28       4
92487       172       5
94019       122       3
96699       152       5
99073        94       2

[272 rows x 2 columns]

In [89]:
# creating array for user 1

u1_list=[] # user 1 empty list
for i in u1['movie_id']: # from user1 movie id
    f = movie_vector[i].values # already created movie vector contains 18 categories.values
    u1_list.append(f) # and that value will get store in list
#     print(f)
u1_list

[array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [43]:
#converting u1 data to df
uu1 = pd.DataFrame(u1_list,columns=range(1,19))
uu1

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
1     0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   1   0   0   0   0   0   1   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
267   1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0
268   1   1   0   0   0   0   0   1   0   0   0   0   0   1   1   0   1   0
269   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
270   0   0   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[272 rows x 18 columns]

In [90]:
# creating single vector for one user, this will show like for 18 categories the vecor will get create 
vec=[]
for j in range(1,19):
    g = sum(uu1[j]) # uu1+18/count
    vec.append(g/272) 
vec   

[0.23529411764705882,
 0.12867647058823528,
 0.007352941176470588,
 0.03308823529411765,
 0.20588235294117646,
 0.0661764705882353,
 0.0,
 0.20955882352941177,
 0.007352941176470588,
 0.0,
 0.051470588235294115,
 0.014705882352941176,
 0.011029411764705883,
 0.1213235294117647,
 0.08088235294117647,
 0.12867647058823528,
 0.05514705882352941,
 0.03308823529411765]

In [107]:
# create a vector list for whole user and movie vector

vector =[]
for user in range(1,944): # total unique users are 943
    users = ratings[ratings['user_id']==user][['movie_id','rating']] # for all user id 
    users_list=[] # for storing user list
    for i in users['movie_id']:
        f = movie_vector[i].values # to get user movie id based on category
        users_list.append(f)
    user_df = pd.DataFrame(u1_list,columns=range(1,19))
    vec=[]
    for j in range(1,19): # to convert vectors to single value
        g = sum(user_df[j])
        vec.append(g/len(u1))
    vector.append(vec)
# return vector
print(vector)
# user_df

[[0.2757352941176471, 0.15441176470588236, 0.04411764705882353, 0.09191176470588236, 0.33455882352941174, 0.09191176470588236, 0.01838235294117647, 0.39338235294117646, 0.007352941176470588, 0.003676470588235294, 0.04779411764705882, 0.04779411764705882, 0.01838235294117647, 0.16176470588235295, 0.15808823529411764, 0.19117647058823528, 0.09191176470588236, 0.022058823529411766], [0.2757352941176471, 0.15441176470588236, 0.04411764705882353, 0.09191176470588236, 0.33455882352941174, 0.09191176470588236, 0.01838235294117647, 0.39338235294117646, 0.007352941176470588, 0.003676470588235294, 0.04779411764705882, 0.04779411764705882, 0.01838235294117647, 0.16176470588235295, 0.15808823529411764, 0.19117647058823528, 0.09191176470588236, 0.022058823529411766], [0.2757352941176471, 0.15441176470588236, 0.04411764705882353, 0.09191176470588236, 0.33455882352941174, 0.09191176470588236, 0.01838235294117647, 0.39338235294117646, 0.007352941176470588, 0.003676470588235294, 0.04779411764705882, 0.

In [104]:
# created funct

def user_vector(ratings,movie_vector):
    vector =[]
    for user in range(1,944):
        u1 = ratings[ratings['user_id']==user][['movie_id','rating']]
        u1_list=[]
        for i in u1['movie_id']:
            f = movie_vector[i].values
            u1_list.append(f)
        uu1 = pd.DataFrame(u1_list,columns=range(1,19))
        vec=[]
        for j in range(1,19):
            g = sum(uu1[j])
            vec.append(g/len(u1))
        vector.append(vec)
        
    return vector

In [105]:
vector = user_vector(ratings,movie_vector)
vector

[[0.2757352941176471,
  0.15441176470588236,
  0.04411764705882353,
  0.09191176470588236,
  0.33455882352941174,
  0.09191176470588236,
  0.01838235294117647,
  0.39338235294117646,
  0.007352941176470588,
  0.003676470588235294,
  0.04779411764705882,
  0.04779411764705882,
  0.01838235294117647,
  0.16176470588235295,
  0.15808823529411764,
  0.19117647058823528,
  0.09191176470588236,
  0.022058823529411766],
 [0.16129032258064516,
  0.04838709677419355,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.14516129032258066,
  0.0,
  0.5645161290322581,
  0.016129032258064516,
  0.03225806451612903,
  0.03225806451612903,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.06451612903225806,
  0.1935483870967742,
  0.04838709677419355,
  0.0],
 [0.25925925925925924,
  0.07407407407407407,
  0.0,
  0.0,
  0.2222222222222222,
  0.18518518518518517,
  0.018518518518518517,
  0.4074074074074074,
  0.0,
  0.037037037037037035,
  0.0925925925925

In [108]:
user_vector = pd.DataFrame(vector)
user_vector

0         1         2         3         4         5         6   \
0    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
1    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
2    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
3    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
4    0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
..        ...       ...       ...       ...       ...       ...       ...   
938  0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
939  0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
940  0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
941  0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   
942  0.275735  0.154412  0.044118  0.091912  0.334559  0.091912  0.018382   

           7         8         9         10        11        12        13  \
0    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
1    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
2    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
3    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
4    0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
..        ...       ...       ...       ...       ...       ...       ...   
938  0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
939  0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
940  0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
941  0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   
942  0.393382  0.007353  0.003676  0.047794  0.047794  0.018382  0.161765   

           14        15        16        17  
0    0.158088  0.191176  0.091912  0.022059  
1    0.158088  0.191176  0.091912  0.022059  
2    0.158088  0.191176  0.091912  0.022059  
3    0.158088  0.191176  0.091912  0.022059  
4    0.158088  0.191176  0.091912  0.022059  
..        ...       ...       ...       ...  
938  0.158088  0.191176  0.091912  0.022059  
939  0.158088  0.191176  0.091912  0.022059  
940  0.158088  0.191176  0.091912  0.022059  
941  0.158088  0.191176  0.091912  0.022059  
942  0.158088  0.191176  0.091912  0.022059  

[943 rows x 18 columns]

In [110]:
# dot mat
content_vector = np.dot(user_vector,movie_vector)
content_vector # to get content vector we need uservec * movie vec

array([[0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       [0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       [0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       ...,
       [0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       [0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235],
       [0.47058824, 0.62132353, 0.19117647, ..., 0.55514706, 0.33455882,
        0.39338235]])

In [113]:
content_vector = pd.DataFrame(content_vector)
content_vectors = content_vector.T
content_vectors

0         1         2         3         4         5         6    \
0     0.470588  0.470588  0.470588  0.470588  0.470588  0.470588  0.470588   
1     0.621324  0.621324  0.621324  0.621324  0.621324  0.621324  0.621324   
2     0.191176  0.191176  0.191176  0.191176  0.191176  0.191176  0.191176   
3     1.003676  1.003676  1.003676  1.003676  1.003676  1.003676  1.003676   
4     0.676471  0.676471  0.676471  0.676471  0.676471  0.676471  0.676471   
...        ...       ...       ...       ...       ...       ...       ...   
1677  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382   
1678  0.352941  0.352941  0.352941  0.352941  0.352941  0.352941  0.352941   
1679  0.555147  0.555147  0.555147  0.555147  0.555147  0.555147  0.555147   
1680  0.334559  0.334559  0.334559  0.334559  0.334559  0.334559  0.334559   
1681  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382   

           7         8         9    ...       933       934       935  \
0     0.470588  0.470588  0.470588  ...  0.470588  0.470588  0.470588   
1     0.621324  0.621324  0.621324  ...  0.621324  0.621324  0.621324   
2     0.191176  0.191176  0.191176  ...  0.191176  0.191176  0.191176   
3     1.003676  1.003676  1.003676  ...  1.003676  1.003676  1.003676   
4     0.676471  0.676471  0.676471  ...  0.676471  0.676471  0.676471   
...        ...       ...       ...  ...       ...       ...       ...   
1677  0.393382  0.393382  0.393382  ...  0.393382  0.393382  0.393382   
1678  0.352941  0.352941  0.352941  ...  0.352941  0.352941  0.352941   
1679  0.555147  0.555147  0.555147  ...  0.555147  0.555147  0.555147   
1680  0.334559  0.334559  0.334559  ...  0.334559  0.334559  0.334559   
1681  0.393382  0.393382  0.393382  ...  0.393382  0.393382  0.393382   

           936       937       938       939       940       941       942  
0     0.470588  0.470588  0.470588  0.470588  0.470588  0.470588  0.470588  
1     0.621324  0.621324  0.621324  0.621324  0.621324  0.621324  0.621324  
2     0.191176  0.191176  0.191176  0.191176  0.191176  0.191176  0.191176  
3     1.003676  1.003676  1.003676  1.003676  1.003676  1.003676  1.003676  
4     0.676471  0.676471  0.676471  0.676471  0.676471  0.676471  0.676471  
...        ...       ...       ...       ...       ...       ...       ...  
1677  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  
1678  0.352941  0.352941  0.352941  0.352941  0.352941  0.352941  0.352941  
1679  0.555147  0.555147  0.555147  0.555147  0.555147  0.555147  0.555147  
1680  0.334559  0.334559  0.334559  0.334559  0.334559  0.334559  0.334559  
1681  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  0.393382  

[1682 rows x 943 columns]

In [131]:
content_vectors.to_csv("content_vector.csv",index=False)

In [132]:
def content_based(ratings,content_vectors,userid,thresh):
    u2=ratings[ratings['user_id']==userid]['movie_id'].values
    val=content_vectors[content_vectors[userid]>(content_vectors[userid].max()-thresh)]
    recom=[]
    for i in val.index:
        if(i in u2):
            pass
        else:
            recom.append(i)
    return recom

In [135]:
content_based(ratings,content_vectors,9,0.2)

[171, 854, 1137]